# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'ENI – VS Enterprise – MPN (b570f9c6-8200-4c2f-a8e1-a43579c9939e)'
    appType: 'webApp'
    WebAppName: 'eni-html'
    packageForLinux: '$(System.DefaultWorkingDirectory)/'
